version: "3.7"
services:
  alpha:
    image: mariadb/server
    command: ["mysqld",
        "--server_id=1",
        "--binlog_checksum=NONE",
        "--log_bin",
        "--log_basename=alpha",
        "--log_slave_updates=ON",
        "--slave-parallel-mode=optimistic",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve"]
    env_file: ./.env
    ports:
      - 3301:3306
    volumes:
      - ../dbdata/alpha:/var/lib/mysql
      - ./mariadb.conf.d/replication.cnf:/etc/mysql/mariadb.conf.d/replication.cnf
  bravo:
    image: mariadb/server
    command: ["mysqld",
        "--server_id=2",
        "--binlog_checksum=NONE",
        "--log_bin",
        "--log_slave_updates=ON",
        "--slave-parallel-mode=optimistic",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve"]
    env_file: ./.env
    ports:
      - 3302:3306
    volumes:
      - ../dbdata/bravo:/var/lib/mysql
      - ./mariadb.conf.d/replication.cnf:/etc/mysql/mariadb.conf.d/replication.cnf

networks:
  default:
    external:
      name: kfe-network
